import assert from 'node:assert/strict';
import { acquireMicrophone, hasAudibleSignal, microphoneConstraints, microphoneMessage, readInputDevice, saveInputDevice } from '../src/components/cupcake/voiceInput.ts';
import { archiveTalk, continuationContext, drainVoiceTransport, persistTalk, readTalks, saveTalk, TalkLineDrain, VoiceEndingCoordinator } from '../src/components/cupcake/voiceHistory.ts';

const memory = new Map();
Object.defineProperty(globalThis, 'localStorage', { value: { getItem:key=>memory.get(key)||null, setItem:(key,value)=>memory.set(key,value) } });

assert.deepEqual(microphoneConstraints('synthetic-device'), {audio:{deviceId:{exact:'synthetic-device'},echoCancellation:true,noiseSuppression:true}});
assert.match(microphoneMessage({name:'NotAllowedError'}), /System Settings/);
assert.match(microphoneMessage({name:'NotReadableError'}), /allowed but could not start/);
assert.match(microphoneMessage({name:'MicrophoneTimeoutError'}), /did not finish/);
assert.equal(hasAudibleSignal(new Uint8Array(32).fill(128)).heard, false);
const audible=new Uint8Array(32).fill(128);audible[0]=180;assert.equal(hasAudibleSignal(audible).heard,true);
saveInputDevice('synthetic-device');assert.equal(readInputDevice(),'synthetic-device');
let releaseMic;let lateStopped=false;const delayed=new Promise(resolve=>{releaseMic=resolve});
await assert.rejects(acquireMicrophone(()=>delayed,{},5),e=>e.name==='MicrophoneTimeoutError');
releaseMic({getTracks:()=>[{stop:()=>{lateStopped=true}}]});await new Promise(resolve=>setTimeout(resolve,0));assert.equal(lateStopped,true);
const readyStream={getTracks:()=>[]};assert.equal(await acquireMicrophone(()=>Promise.resolve(readyStream),{},50),readyStream);

const talk={id:'synthetic',title:'Synthetic Talk',startedAt:'2026-09-07T00:00:00Z',endedAt:'2026-09-07T00:01:00Z',lines:Array.from({length:45},(_,i)=>({role:i%2?'Cupcake':'You',text:`line ${i}`}))};
saveTalk(talk);assert.equal(readTalks()[0].lines.length,45);
const context=continuationContext(talk);assert.equal(context.lines.length,40);assert.ok(JSON.stringify(context).length<12000);
const longTalk={...talk,lines:Array.from({length:10},(_,i)=>({role:i%2?'Cupcake':'You',text:`${i}:`+'x'.repeat(1998)}))};
const bounded=continuationContext(longTalk);assert.equal(bounded.lines.length,6);assert.match(bounded.lines.at(-1).text,/^9:/);assert.equal(bounded.lines.reduce((n,x)=>n+x.text.length,0),12000);
archiveTalk(talk.id);assert.equal(readTalks()[0].archived,true);
const drain=new TalkLineDrain();drain.append({role:'You',text:'before'},'event-1');
drain.append({role:'Cupcake',text:'between end and teardown'},'event-2');
assert.equal(drain.append({role:'Cupcake',text:'duplicate reconciliation'},'event-2'),false);
assert.deepEqual(drain.close().map(x=>x.text),['before','between end and teardown']);
assert.equal(drain.append({role:'You',text:'late after teardown'},'event-3'),false);
const originalSet=localStorage.setItem;localStorage.setItem=()=>{throw Error('quota')};
const failed=persistTalk({...talk,id:'save-failure'});assert.equal(failed.talks.some(x=>x.id==='save-failure'),true);assert.equal(failed.persisted,false);
assert.equal(persistTalk({...talk,lines:[{role:'You',text:'new content not saved'}]}).persisted,false,'an older saved record must not count as saving its new contents');localStorage.setItem=originalSet;
const coordinator=new VoiceEndingCoordinator();let runs=0;let reentered;
const first=coordinator.begin(async()=>{runs++;reentered=coordinator.begin(async()=>{runs++});drain.append({role:'You',text:'final during teardown'},'event-4');throw Error('leave failed');});
await Promise.resolve();assert.equal(first,reentered);await assert.rejects(first,/leave failed/);assert.equal(runs,1);assert.equal(coordinator.current,null);
const finalDrain=new TalkLineDrain();let leaveDone,destroyDone;const order=[];let duplicate;
const transport={leave:()=>{order.push('leave');duplicate=coordinator.begin(async()=>{throw Error('duplicate cleanup')});return new Promise(resolve=>{leaveDone=resolve});},destroy:()=>{order.push('destroy');return new Promise(resolve=>{destroyDone=resolve});}};
let saved;
const ending=coordinator.begin(async()=>{saved=await drainVoiceTransport(transport,finalDrain,1000);order.push('save');});
await new Promise(resolve=>setTimeout(resolve,0));assert.equal(duplicate,ending);
assert.equal(finalDrain.append({role:'You',text:'last user phrase'},'final-1'),true);leaveDone();
await new Promise(resolve=>setTimeout(resolve,0));assert.deepEqual(order,['leave','destroy']);
assert.equal(finalDrain.append({role:'Cupcake',text:'last reply'},'final-2'),true);destroyDone();await ending;
assert.deepEqual(saved.map(x=>x.text),['last user phrase','last reply']);assert.deepEqual(order,['leave','destroy','save']);
assert.equal(finalDrain.append({role:'You',text:'too late'},'late'),false);
let destroyedAfterThrow=false;
await drainVoiceTransport({leave:()=>{throw Error('synchronous leave failure')},destroy:()=>{destroyedAfterThrow=true;return Promise.reject(Error('destroy failure'))}},new TalkLineDrain(),10);
assert.equal(destroyedAfterThrow,true);
let timedOutDestroy=false;
await drainVoiceTransport({leave:()=>new Promise(()=>{}),destroy:()=>{timedOutDestroy=true;return new Promise(()=>{})}},new TalkLineDrain(),5);
assert.equal(timedOutDestroy,true,'teardown must finish even when provider promises never settle');
console.log('PASS voice input diagnostics and bounded local Talk recovery history');
