import { useState } from 'react';
import { ArrowLeft, ArrowUpRight, Mail } from 'lucide-react';
import '../../components/experience/experience.css';

export default function ContactUs(){
 const [name,setName]=useState('');const[email,setEmail]=useState('');const[message,setMessage]=useState('');
 const submit=(event:React.FormEvent)=>{event.preventDefault();const subject=encodeURIComponent(`Hales.ai project inquiry — ${name.trim()}`);const body=encodeURIComponent(`Name: ${name.trim()}\nReply email: ${email.trim()}\n\n${message.trim()}`);window.location.href=`mailto:matt@hales.ai?subject=${subject}&body=${body}`;};
 return <main className="hx" style={{minHeight:'100vh'}}><section className="hx-section"><a className="hx-text-button" href="/"><ArrowLeft size={18}/> Back to Hales.ai</a><div className="hx-studio" style={{marginTop:35,paddingTop:50}}><div><p className="hx-eyebrow">LET’S BUILD SOMETHING USEFUL.</p><h1 style={{fontSize:'clamp(48px,5vw,80px)',margin:'25px 0'}}>Bring us the<br/><em>messy problem.</em></h1><p>Tell us what happens today, where the friction is, and who needs a better way to work.</p><a href="mailto:matt@hales.ai"><Mail size={18}/> matt@hales.ai</a><p style={{marginTop:25}}>Based in Texas. Working across enterprise operations, conversational AI, and the field.</p></div><form onSubmit={submit} className="hx-contact-form"><label>Your name<input required maxLength={120} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Your email<input required type="email" maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>What would you like to build?<textarea required maxLength={4000} rows={5} value={message} onChange={e=>setMessage(e.target.value)}/></label><button type="submit" className="hx-button">Open email draft <ArrowUpRight size={18}/></button><p style={{fontSize:14,marginTop:18}}>Opens your email app so you can review and send. Nothing is sent by this page.</p></form></div></section></main>;
}
