import { useState } from 'react';
import AnswerText from './AnswerText';
import { ArrowLeft, Check, Copy, Download, FileText, Loader2, Send } from 'lucide-react';
import { analysisPacket, conversationPacket, libraryRequest, openPrint, safeFilename, saveFile, sourceText, type Analysis, type Conversation, type Source } from './library';

export function SourceList({ sources }: { sources?: Source[] }) {
  if (!sources?.length) return null;
  return <details className="cc-sources"><summary>{sources.length} retrieved passage{sources.length===1?'':'s'} · {new Set(sources.map(s=>s.documentId||s.id||s.url||s.title)).size} source document(s) · open originals</summary><ul>{sources.map((s, i) => <li key={i}>{s.url?.startsWith('https://hales.ai/cupcake?')?<a href={s.url} target="_blank" rel="noopener noreferrer">{sourceText({ ...s, url: undefined })} ↗</a>:sourceText({ ...s, url: undefined })}{s.text && <blockquote>{s.text}</blockquote>}</li>)}</ul></details>;
}
export function AnalysisCard({ analysis }: { analysis: Analysis }) {
  const [copied, setCopied] = useState(false); const [error, setError] = useState('');
  const [decisionOpen,setDecisionOpen]=useState(false);const [decision,setDecision]=useState('');const [saving,setSaving]=useState(false);const [saved,setSaved]=useState(false);
  async function saveDecision(){if(!decision.trim()||saving)return;setSaving(true);setError('');try{await libraryRequest({action:'decision_save',text:decision.trim(),type:'decision',status:'open',sourceIds:[...new Set((analysis.sources||[]).map(s=>s.documentId).filter((id):id is string=>!!id&&/^(doc|rec|analysis|project)_[a-f0-9]{32}$/.test(id)))].slice(0,12)});setSaved(true);setDecisionOpen(false);setDecision('');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  return <article className="cc-analysis"><div className="cc-analysis-meta"><span>{analysis.model || 'Saved analysis'}</span>{analysis.createdAt && <time>{new Date(analysis.createdAt).toLocaleString()}</time>}</div>{analysis.message && <h3>{analysis.message}</h3>}<AnswerText text={analysis.reply||''}/><SourceList sources={analysis.sources} /><div className="cc-answer-actions"><button className="cc-text-button" onClick={() => void navigator.clipboard.writeText(analysis.reply || '').then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000); }).catch(() => setError('Copy is unavailable in this browser. Use Download instead.'))}>{copied ? <Check size={15} /> : <Copy size={15} />}{copied ? 'Copied' : 'Copy answer'}</button><button className="cc-text-button" onClick={() => saveFile(analysisPacket(analysis), `${safeFilename(analysis.message || 'Cupcake analysis')}.md`)}><Download size={15} />Download answer</button><button className="cc-text-button" onClick={()=>{setDecisionOpen(v=>!v);setSaved(false);}}>Save a decision</button></div>{decisionOpen&&<div className="cc-decision-form"><label className="cc-label">What have you decided?<textarea rows={3} value={decision} onChange={e=>setDecision(e.target.value)} maxLength={4000} placeholder="In your own words: what to do, what to avoid, or what to remember…"/></label><p className="cc-muted cc-small">Your reviewed decision goes into the decision register and becomes searchable across Cupcake. The AI's proposal and original source stay unchanged.</p><button className="cc-primary" disabled={saving||!decision.trim()} onClick={()=>void saveDecision()}>{saving?'Saving…':'Save my decision'}</button></div>}{saved&&<p className="cc-notice" role="status">Your decision is saved in the private library.</p>}{error && <p role="alert">{error}</p>}</article>;
}

export default function ConversationPanel({ record, onClose, onAsk, onRetry, onOrganized, asking, questionError, retrying = false }: {
  record: Conversation; onClose: () => void; onAsk: (message: string) => Promise<void>; onRetry?: () => void;
  asking: boolean; questionError?: string; retrying?: boolean; onOrganized?: (project:string,tags:string[])=>void;
}) {
  const [question, setQuestion] = useState(''); const [exportError, setExportError] = useState('');
  const [organizing,setOrganizing]=useState(false);const [organizeLoading,setOrganizeLoading]=useState(false);const [project,setProject]=useState(record.project||'');const [topics,setTopics]=useState((record.tags||[]).join(', '));const [organizeError,setOrganizeError]=useState('');
  async function openOrganization(){setOrganizing(true);setOrganizeLoading(true);setOrganizeError('');try{const d=await libraryRequest<{document:Conversation}>({action:'fetch',id:record.id});setProject(d.document.project||'');setTopics((d.document.tags||[]).join(', '));}catch(e){setOrganizeError((e as Error).message);}finally{setOrganizeLoading(false);}}
  async function saveOrganization(){if(organizeLoading||organizeError)return;setOrganizeLoading(true);const tags=topics.split(',').map(t=>t.trim()).filter(Boolean);try{await libraryRequest({action:'tag',id:record.id,project:project.trim(),tags});onOrganized?.(project.trim(),tags);setOrganizing(false);}catch(e){setOrganizeError((e as Error).message);}finally{setOrganizeLoading(false);}}
  const ready = record.status === 'ready';
  const isRecording = record.kind === 'recording' || !!record.transcript;
  const sourceType = isRecording ? 'Recording' : record.kind === 'note' ? 'Imported note' : 'Imported conversation';
  const latestModel = [...(record.chat || [])].reverse().find(m => m.role !== 'user' && m.model)?.model || record.chatModel;
  async function submit() { const message = question.trim(); if (!message || asking || !ready) return; try { await onAsk(message); setQuestion(''); } catch { /* Keep the draft question for retry. */ } }
  return <div className="cc-detail" role="dialog" aria-modal="false" aria-label="Conversation details">
    <button className="cc-text-button" onClick={onClose}><ArrowLeft size={17} />Back to library</button>
    <div className="cc-analysis-meta"><span>{record.sourceApp ? `${record.sourceApp} · ${sourceType}` : sourceType}</span><time>{new Date(record.createdAt).toLocaleString()}</time></div>
    <h2>{record.title}</h2>
    <div className="cc-heading-row"><span className="cc-muted cc-small">{record.project||'Unfiled'}{record.tags?.length?` · ${record.tags.join(' · ')}`:''}</span><button className="cc-text-button" onClick={()=>void openOrganization()}>Organize</button></div>
    {organizing&&<div className="cc-card"><label className="cc-label">Project<input value={project} onChange={e=>setProject(e.target.value)} disabled={organizeLoading} maxLength={120} placeholder="Choose a useful project or area"/></label><label className="cc-label">Topics, separated by commas<input value={topics} onChange={e=>setTopics(e.target.value)} disabled={organizeLoading} maxLength={400} placeholder="strategy, follow-up, product"/></label>{organizeError&&<p role="alert">{organizeError}</p>}<div className="cc-action-row"><button className="cc-primary" disabled={organizeLoading||!!organizeError} onClick={()=>void saveOrganization()}>{organizeLoading?'Loading…':'Save organization'}</button><button className="cc-text-button" onClick={()=>setOrganizing(false)}>Cancel</button></div></div>}
    <div className="cc-export-bar"><span><FileText size={17} />Complete conversation packet</span><div><button onClick={() => saveFile(conversationPacket(record), `${safeFilename(record.title)}.md`)}>Markdown</button><button onClick={() => saveFile(conversationPacket(record, 'text'), `${safeFilename(record.title)}.txt`, 'text/plain;charset=utf-8')}>Text</button><button onClick={() => { try { openPrint(record.title, conversationPacket(record, 'text')); } catch (e) { setExportError((e as Error).message); } }}>PDF / Print</button></div></div>
    <p className="cc-muted cc-small">Includes the source, summary, commitments, saved questions and answers, and available model details. Markdown works well for bringing selected context into another AI.</p>
    {exportError && <p role="alert" className="cc-error">{exportError}</p>}
    {!ready && <div className="cc-card"><strong>{record.status === 'failed' ? 'Processing needs attention' : record.status === 'uploading' ? 'Your recording is uploading' : 'Preparing your transcript…'}</strong>{record.error && <p role="alert">{record.error}</p>}<p>{record.phase || record.status}{record.progress ? ` · ${record.progress.completed} / ${record.progress.total} sections` : ''}</p><p className="cc-muted">{record.status === 'uploading' ? 'Keep the uploading device and page open until the transfer finishes.' : 'Your original is retained. Processing continues when you leave this page.'}</p>{record.status === 'failed' && onRetry && <button className="cc-primary" disabled={retrying} onClick={onRetry}>Retry incomplete processing</button>}</div>}
    <section className="cc-conversation-ask"><h3>Think this through with Cupcake</h3><p className="cc-muted">Ask for a strategy, challenge an assumption, compare options, or pull out the next move. Answers stay with this conversation.</p>{latestModel && <span className="cc-model-badge">Last answer · {latestModel}</span>}
      {(record.chat || []).map((m, i) => m.role === 'user' ? <div className="cc-question-bubble" key={i}><strong>You</strong><p>{m.text || m.content}</p></div> : <AnalysisCard key={i} analysis={{ reply: m.text || m.content, model: m.model, createdAt: m.createdAt, sources: m.sources }} />)}
      {record.analyses?.map((a, i) => <AnalysisCard key={a.id || i} analysis={a} />)}
      {asking && <div className="cc-thinking" role="status" aria-live="polite"><Loader2 className="cc-spin" size={18} /><span>Cupcake is reading the evidence and thinking…<small>Long conversations can take a minute or two. Your question is being processed.</small></span></div>}
      {questionError && <div className="cc-error" role="alert">{questionError}</div>}
      {!ready && <p className="cc-muted">Questions become available after transcription finishes.</p>}
      <form className="cc-ask" onSubmit={e => { e.preventDefault(); void submit(); }}><textarea aria-label="Question about this conversation" value={question} onChange={e => setQuestion(e.target.value)} maxLength={4000} rows={3} disabled={asking} placeholder="Challenge my plan. What am I missing, and what would you do next?" /><button className="cc-primary" disabled={asking || !question.trim() || !ready} aria-label="Ask Cupcake">{asking ? <Loader2 className="cc-spin" size={18} /> : <Send size={18} />}</button></form>
    </section>
    {isRecording ? <><h3>Summary</h3><p className="cc-answer-text">{record.summary || 'No summary saved.'}</p>{!!record.keyPoints?.length && <ul>{record.keyPoints.map((p, i) => <li key={i}>{p}</li>)}</ul>}
      <h3>Commitments to review</h3>{record.commitments?.length ? record.commitments.map((c, i) => <div className="cc-card" key={i}><strong>{c.text}</strong><p>{c.owner || 'Owner unclear'} · {c.dueDate || 'No date stated'}</p>{c.evidence && <blockquote>{c.evidence}</blockquote>}</div>) : <p className="cc-muted">{ready ? 'No explicit commitments identified.' : 'Commitments will appear after processing.'}</p>}
      <details><summary>Read full transcript</summary><pre>{record.transcript || 'Not available yet.'}</pre></details>
    </> : <><h3>{sourceType}</h3><p className="cc-answer-text">{record.text || 'Imported content is not available yet.'}</p></>}
    <p className="cc-muted cc-small">Source text and AI conclusions remain separate. No actions are taken from these notes.</p>
  </div>;
}
