import { libraryRequest } from './library';
import type { DashboardEntry, DashboardRange } from './DashboardView';
export type WeightCorrection={operation:'replace'|'exclude';originalLb:number;reportedLb?:number;reason:string;recordedAt:string};
export type WeightRecord={id:string;kind:'measurement';weightLb:number;measuredAt:string;source:string;recordId:string;basis?:'owner_corrected'|'health_connect';correction?:WeightCorrection};
export type WeightPage={measurements:WeightRecord[];latestMeasurement:WeightRecord|null;excludedMeasurements?:WeightRecord[];excludedTotal?:number;nextCursor:string|null;total:number;coverage:{initialSince:string|null;lastSyncAt:string|null;lastObservedAt:string|null;resetCount:number}};
export function centralMidnight(date:string){let ms=Date.parse(date+'T00:00:00Z');for(let i=0;i<3;i++){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));const represented=Date.parse(`${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:${p.second}Z`);ms+=Date.parse(date+'T00:00:00Z')-represented;}return new Date(ms).toISOString();}
export function weightBounds(range:DashboardRange){if(range.preset==='all')return {};const end=new Date(range.end+'T12:00:00Z');end.setUTCDate(end.getUTCDate()+1);return {start:centralMidnight(range.start),end:centralMidnight(end.toISOString().slice(0,10))};}
export async function loadWeightPage(range?:DashboardRange,cursor?:string){return libraryRequest<WeightPage>({action:'weight_list',limit:200,...(range?weightBounds(range):{}),...(cursor?{cursor}:{})});}
export function weightEntry(r:WeightRecord):DashboardEntry {
 const excluded=r.correction?.operation==='exclude',corrected=r.basis==='owner_corrected'&&r.correction?.operation==='replace';
 const original=r.correction?.originalLb;
 const body=excluded?`${r.weightLb.toFixed(1)} lb · excluded by you. This original reading is preserved but does not affect your weight graph or totals.`:corrected?`${r.weightLb.toFixed(1)} lb · corrected by you. Original scale reading: ${typeof original==='number'&&Number.isFinite(original)?original.toFixed(1):'unavailable'} lb. The original measurement time is unchanged.`:`${r.weightLb.toFixed(1)} lb · measured`;
 const correctionNote=r.correction?[r.correction.reason?`Reason: ${r.correction.reason}`:'',r.correction.recordedAt?`Correction saved: ${r.correction.recordedAt}`:''].filter(Boolean).join('\n'):'';
 return {id:'weight:'+r.id,type:'activity',date:new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(r.measuredAt)),title:excluded?'Excluded weight reading':corrected?'Corrected weigh-in':'Weight measurement',body:[body,correctionNote].filter(Boolean).join('\n'),amount:r.weightLb,details:{weightKind:excluded?'excluded':'measurement',weightLb:r.weightLb,measuredAt:r.measuredAt,recordId:r.recordId,source:r.source,weightBasis:r.basis||'health_connect',weightCorrection:r.correction,originalWeightLb:original}};
}
