import {useCallback,useEffect,useRef,useState,type ComponentProps} from 'react';
import {WeightHistory} from './WeightHistory';
import {loadWeightPage,weightEntry,type WeightPage} from './weightApi';
export function WeightHistoryConnected(props:ComponentProps<typeof WeightHistory>){
 const [page,setPage]=useState<WeightPage|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const generation=useRef(0),flight=useRef(false);
 const load=useCallback(async()=>{const g=++generation.current;flight.current=false;setPage(null);setBusy(true);setError('');try{const next=await loadWeightPage(props.range);if(g===generation.current)setPage(next);}catch(e){if(g===generation.current)setError(e instanceof Error?e.message:'Weight history unavailable.');}finally{if(g===generation.current)setBusy(false);}},[props.range]);
 useEffect(()=>{void load();const current=generation.current;return()=>{generation.current=current+1;};},[load]);
 const more=async()=>{if(!page?.nextCursor||flight.current)return;flight.current=true;const g=generation.current;setBusy(true);setError('');try{const next=await loadWeightPage(props.range,page.nextCursor);if(g===generation.current)setPage(current=>current?{...next,measurements:[...current.measurements,...next.measurements.filter(n=>!current.measurements.some(p=>p.id===n.id))]}:next);}catch(e){if(g===generation.current)setError(e instanceof Error?e.message:'Could not load older weights.');}finally{if(g===generation.current){flight.current=false;setBusy(false);}}};
 return <><WeightHistory {...props} entries={[...(page?.measurements||[]).map(weightEntry),...props.entries.filter(e=>e.type==='activity'&&e.details?.weightKind!=='measurement')]} loading={busy&&!page} error={error||props.error} hasMore={!!page?.nextCursor} loadingMore={busy} onMore={()=>void more()} onRefresh={()=>{void load();props.onRefresh();}}/>{page&&<p className="cc-muted cc-small">{page.measurements.length} of {page.total} individual measurements loaded. {page.coverage.initialSince?`History available since ${page.coverage.initialSince}.`:'Initial phone history has not been confirmed.'} {page.coverage.lastSyncAt?`Last phone sync: ${page.coverage.lastSyncAt}.`:'No phone sync recorded yet.'}</p>}</>;
}
