import { useState } from 'react';
import type { DashboardEntry, DashboardRange } from './DashboardView';
import { weightMeasurements, weightTime } from './weightHistoryModel';
import './weight-history.css';
export function WeightHistory({entries,range,loading,error,onBack,onRange,onRefresh,onSelect,hasMore,loadingMore,onMore}:{entries:DashboardEntry[];range:DashboardRange;loading:boolean;error:string;onBack:()=>void;onRange:(preset:DashboardRange['preset'],start?:string,end?:string)=>void;onRefresh:()=>void;onSelect:(entry:DashboardEntry)=>void;hasMore?:boolean;loadingMore?:boolean;onMore?:()=>void}) {
 const axisDate=(at:number)=>new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric'}).format(at);
 const points=weightMeasurements(entries),latest=points[points.length-1],first=points[0];
 const [selectedId,setSelectedId]=useState('');const selected=points.find(p=>p.entry.id===selectedId)||latest;
 const unknown=entries.filter(e=>e.type==='activity'&&!points.some(p=>p.entry.id===e.id));
 const min=Math.min(...points.map(p=>p.lb)),max=Math.max(...points.map(p=>p.lb));const low=Number.isFinite(min)?Math.floor(min-2):0,high=Number.isFinite(max)?Math.ceil(max+2):1;
 const x=(at:number)=>36+(at-(first?.at||0))/Math.max(1,(latest?.at||0)-(first?.at||0))*568,y=(lb:number)=>190-(lb-low)/(high-low)*150;
 return <section className="cc-dashboard cc-weight-history"><button className="cc-text-button" onClick={onBack}>← Back to dashboard</button><div className="cc-heading-row"><div><span className="cc-eyebrow">YOUR WEIGHT, OVER TIME</span><h2>Small shifts.<br/><em>The real picture.</em></h2></div><button className="cc-secondary" onClick={onRefresh} disabled={loading}>Refresh</button></div>
 <div className="cc-dashboard-range" aria-label="Weight history range">{(['day','week','month','custom','all'] as const).map(p=><button key={p} aria-pressed={range.preset===p} onClick={()=>onRange(p)}>{({day:'Today',week:'7 days',month:'30 days',custom:'Custom',all:'All time'})[p]}</button>)}</div>
 {range.preset==='custom'&&<div className="cc-dashboard-dates"><label>From<input type="date" value={range.start} max={range.end} onChange={e=>onRange('custom',e.target.value,range.end)}/></label><label>Through<input type="date" value={range.end} min={range.start} onChange={e=>onRange('custom',range.start,e.target.value)}/></label></div>}
 {error&&<p role="alert" className="cc-error">{error}</p>}{loading?<p role="status">Loading weight history…</p>:error?null:<>
 <div className="cc-weight-glass"><div className="cc-weight-readout" aria-live="polite"><strong>{selected?selected.lb.toFixed(1):'—'} <small>lb</small></strong><span>{selected?`${weightTime(selected.at)} · Central time`:'No timestamped weigh-ins in this range'}</span></div>
 {points.length>0?<><svg viewBox="0 0 640 230" role="img" aria-label={`${points.length} timestamped weight measurements in pounds. Select a measurement below for details.`}>{[low,(low+high)/2,high].map(v=><g key={v}><line x1="36" x2="604" y1={y(v)} y2={y(v)} stroke="currentColor" opacity=".12"/><text x="36" y={y(v)-8} fill="currentColor" fontSize="11" opacity=".65">{v.toFixed(1)} lb</text></g>)}{points.length>1&&<polyline points={points.map(p=>`${x(p.at)},${y(p.lb)}`).join(' ')} fill="none" stroke="#ef9bac" strokeWidth="3" strokeLinejoin="round"/>}{points.map(p=><circle key={p.entry.id} cx={points.length===1?320:x(p.at)} cy={y(p.lb)} r={selected?.entry.id===p.entry.id?7:4} fill="#ffcad5" stroke="#492434" strokeWidth="2"/>)}<text x="36" y="222" fill="currentColor" fontSize="12">{axisDate(first.at)}</text>{points.length>1&&<text x="604" y="222" textAnchor="end" fill="currentColor" fontSize="12">{axisDate(latest!.at)}</text>}</svg><p className="cc-muted cc-small">{points.length} measured {points.length===1?'reading':'readings'} · {points.length>1?`${(latest!.lb-first.lb)>0?'+':''}${(latest!.lb-first.lb).toFixed(1)} lb from first to last`:'One reading is a starting point, not a trend.'}</p></>:<p className="cc-muted">Your next timestamped scale reading will appear here. Older averages stay below, separate from your weigh-ins.</p>}</div>
 <div className="cc-weight-points" aria-label="Select a weight measurement">{[...points].reverse().map(p=><div key={p.entry.id}><button aria-pressed={selected?.entry.id===p.entry.id} onClick={()=>setSelectedId(p.entry.id)}><strong>{p.lb.toFixed(1)} lb</strong><span>{weightTime(p.at)}</span></button><button className="cc-text-button" onClick={()=>onSelect(p.entry)}>Details →</button></div>)}</div>
 {hasMore&&<button className="cc-secondary" disabled={loadingMore} onClick={onMore}>{loadingMore?'Loading…':'Load older weight records'}</button>}
 {unknown.length>0&&<div className="cc-card"><h3>Other weight records</h3><p className="cc-muted">Averages and records without a measurement time are not plotted as individual weigh-ins.</p>{unknown.map(e=><button className="cc-dashboard-entry" key={e.id} onClick={()=>onSelect(e)}><span><strong>{e.body||'Weight record'}</strong><small>{e.details?.weightKind==='aggregate'?`Aggregate ${String(e.details.aggregateStatistic||'value')}`:'Measurement type unverified'} · uploaded {e.date} {e.time||''}</small></span></button>)}</div>}</>}
 </section>;
}
